#!/usr/bin/python3
"""Streamlit app that verifies and previews an uploaded .eln file.

Run locally with:

    pip install -r tools/requirements.txt
    streamlit run tools/checkELN.py

The checks are not reimplemented here. This app is only an upload front end
for ``tests/checks.py``, so the web tool and the CI suite always agree about
what a valid .eln file is.
"""
import sys
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

import streamlit as st
import streamlit.components.v1 as components

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPOSITORY_ROOT/'tests'))

from checks import checkUploadedFile  # noqa: E402  (needs the path above)

PREVIEW_FILE = 'ro-crate-preview.html'
REPOSITORY_URL = 'https://github.com/TheELNConsortium/TheELNFileFormat'

st.set_page_config(page_title='.eln file checker', layout='wide')
st.markdown(
    """
    <style>
        .stApp {font-size: 20px;}
        .stMarkdown p, .stMarkdown li {font-size: 20px;}
        [data-testid="stFileUploader"] * {font-size: 20px !important;}
        [data-testid="stExpander"] * {font-size: 20px !important;}
    </style>
    """,
    unsafe_allow_html=True,
)

st.markdown('## Tools for the .eln file')
st.markdown(
    'The .eln file format is an archive format for exchanging experimental '
    'results and data. It can be written and read by software such as '
    f'Electronic Laboratory Notebooks. For more information visit '
    f'[the specification repository]({REPOSITORY_URL}).'
)
st.markdown(
    '1. Verify that a file conforms to the .eln format and is not corrupt.'
)
st.markdown(
    '2. Preview the content of a .eln file. The preview is generated by the '
    'software that created the file, not by this page.'
)

uploadedFile = st.file_uploader(
    'Choose an .eln file for verification and preview', type=['eln']
)

if uploadedFile is not None:
    st.markdown(
        """
        <style>
        .stTabs [data-baseweb="tab-list"] button [data-testid="stMarkdownContainer"] p {
            font-size: 36px;
        }
        </style>
        """,
        unsafe_allow_html=True,
    )
    tabVerify, tabPreview = st.tabs(['Verify', 'Preview'])

    with tabVerify:
        st.markdown('### Test summary:')
        results = checkUploadedFile(uploadedFile, uploadedFile.name)
        passed = sum(1 for _label, success, _log in results if success)
        st.markdown(f'{passed} of {len(results)} checks passed.')
        for label, success, log in results:
            heading = ('Success: ' if success else 'FAILURE: ')+label
            with st.expander(heading, icon='✅' if success else '❌'):
                st.code(log if log else 'Success')

    with tabPreview:
        try:
            with ZipFile(uploadedFile, 'r', compression=ZIP_DEFLATED) as elnFile:
                previewFiles = [
                    i for i in elnFile.namelist() if i.endswith(PREVIEW_FILE)
                ]
                if previewFiles:
                    htmlStr = elnFile.read(previewFiles[0]).decode('utf-8')
                    components.html(
                        htmlStr, height=800, width=None, scrolling=True
                    )
                else:
                    st.info(
                        f'This file contains no {PREVIEW_FILE}, so there is '
                        'nothing to preview. The preview is optional and its '
                        'absence is not a validation failure.'
                    )
        except Exception as error:  # noqa: BLE001 - report instead of crashing
            st.error(f'The preview could not be read: {error}')
