#!/usr/bin/python3
"""Streamlit app that verifies and previews an uploaded .eln file.

Run locally with:

    uv run --group tools
    streamlit run tools/checkELN.py

- The checks are not reimplemented here. This app reuses ``tests/checks.py``,
so the web tool and the CI suite always agree about what a valid .eln file is.
"""
import base64
import sys
from pathlib import Path
from zipfile import ZIP_DEFLATED, ZipFile

import streamlit as st

REPOSITORY_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(REPOSITORY_ROOT))
from tests.checks import ALL_TESTS, BaseCheck, PREVIEW_FILE

REPOSITORY_URL = 'https://github.com/TheELNConsortium/TheELNFileFormat'
LOGO_PATH = REPOSITORY_ROOT / 'tools' / 'logo-color-fade.png'

# Configure streamlit layout
st.set_page_config(page_title='.eln file checker', layout='wide')
st.markdown(
    """
    <style>
        .stMarkdown p, .stMarkdown li {font-size: 20px;}
        [data-testid="stFileUploader"] * {font-size: 20px !important;}
        [data-testid="stExpander"] * {font-size: 20px !important;}
        [data-testid="stTab"],
        [data-testid="stTab"] * {font-size: 28px !important;}
    </style>
    """,
    unsafe_allow_html=True,
)

# Header fixed text and logo
col1, col2 = st.columns([0.7, 0.3], vertical_alignment="center")
col1.markdown('## Tools for the .eln file')
col1.markdown('The .eln file format is an archive format for exchanging experimental '
    'results and data. It can be written and read by software such as '
    'Electronic Laboratory Notebooks. For more information visit '
    f'[the specification repository]({REPOSITORY_URL}).'
)
col1.markdown('1. Verify that a file conforms to the .eln format and is not corrupt.')
col1.markdown('2. Preview the content of a .eln file. The preview is generated by the '
              'software that created the file, not by this page.')
if LOGO_PATH.is_file():
    logo_data = base64.b64encode(LOGO_PATH.read_bytes()).decode('ascii')
    col2.markdown(
        f'<div style="text-align: center;">'
        f'<img src="data:image/png;base64,{logo_data}" width="200">'
        '</div>',
        unsafe_allow_html=True,
    )

# Body
uploadedFile = st.file_uploader('Choose an .eln file for verification and preview', type=['eln'])
if uploadedFile is not None:
    tabVerify, tabPreview = st.tabs(['Verify', 'Preview'])

    # Verify tab
    with tabVerify:
        st.markdown('### Test summary:')
        results = BaseCheck.runChecks(uploadedFile, ALL_TESTS, uploadedFile.name)
        passed = sum(1 for _label, success, _log in results if success)
        st.markdown(f'{passed} of {len(results)} checks passed.')
        for label, success, log in results:
            heading = ('Success: ' if success else 'FAILURE: ')+label
            with st.expander(heading, icon='✅' if success else '❌', expanded=bool(log)):
                st.code(log if log else 'Success')
        resultText = '\n'.join([
                f'Test summary: {passed} of {len(results)} checks passed.',
                '',
                *(
                    f'{"Success" if success else "FAILURE"}: {label}\n'
                    f'{log if log else "Success"}'
                    for label, success, log in results
                ),
            ])
        st.markdown('<div style="height: 1rem"></div>', unsafe_allow_html=True)
        with st.expander('Entire report'):
            st.code(resultText, language=None)

    # Preview tab
    with tabPreview:
        try:
            with ZipFile(uploadedFile, 'r', compression=ZIP_DEFLATED) as elnFile:
                previewFiles = [i for i in elnFile.namelist() if i.endswith(PREVIEW_FILE)]
                if previewFiles:
                    htmlStr = elnFile.read(previewFiles[0]).decode('utf-8')
                    st.iframe(htmlStr, height=800, width=None, scrolling=True)
                else:
                    st.info(
                        f'This file contains no {PREVIEW_FILE}, so there is '
                        'nothing to preview. The preview is optional and its '
                        'absence is not a validation failure.'
                    )
        except Exception as error:  # noqa: BLE001 - report instead of crashing
            st.error(f'The preview could not be read: {error}')
